version: "3.8"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0:5000"  # Asigna automáticamente un puerto del host al puerto 5000 del contenedor
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development