version: "3.8"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ":5000"  # Deja que Docker asigne automáticamente el puerto del host
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development