version: "3.8"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:5000"  # Usa la variable de entorno PORT para asignar el puerto dinámicamente
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - GIT_PYTHON_REFRESH=quiet